Certain versions of clang require an explicit initialization for literal const members.
include/clang/Lex/PreprocessorLexer.h:79:3: error: constructor for
'clang::PreprocessorLexer' must explicitly initialize the const member
'FID'

git-svn-id: http://llvm.org/svn/llvm-project/cfe/trunk@315197 91177308-0d34-0410-b5e6-96231b3b80d8