Revert "[Driver] MinGW: Remove custom linker detection"
This reverts rL313102 because it still fails some build bot tests.

On many linux bots it fails with the following error.
error: invalid linker name in argument '-fuse-ld=lld'
and on some windows bots also because there is no ld.lld.exe
lld-link.exe: warning: ignoring unknown argument: -fuse-ld=lld

git-svn-id: http://llvm.org/svn/llvm-project/cfe/trunk@313104 91177308-0d34-0410-b5e6-96231b3b80d8